spring:
  application:
    name: apigw-oauth-test
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: test-call
          uri: http://localhost:8040
          predicates:
            - Path=/test/**
        - id: caller-service
          uri: http://localhost:8020
          predicates:
            - Path=/caller/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: 8oF4WzUd3Xl3gzxONrn8IBylJJCGZuGj
            authorization-grant-type: authorization_code
            scope: openid

server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE